modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-woodenShears//issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-wooden-shears"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="sbmpuntanimal" #mandatory
version="1.0.0" #mandatory
displayName="SBM-Punt-Animal" #mandatory
description='''Push animals without causing damage''' #mandatory

[[dependencies.sbmpuntanimal]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmpuntanimal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"