modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Punt-Animal/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-punt-animal"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="sbmpuntanimal" #mandatory
version="1.0.0" #mandatory
displayName="SBM-Punt-Animal" #mandatory
description='''Push animals without causing damage''' #mandatory

[[dependencies.sbmpuntanimal]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmpuntanimal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"